# 오늘 공부

---
# HTML
- 태그
- 글로벌 속성
  # Python
  - 예외처리
  - 내장함수
---
# HTML
---
### 3.9.3 section 태그
`section 태그`는 웹 페이지에서 논리적으로 관련 있는 내용 영역을 구분할 때 사용합니다. 그래서 보통 section 태그는 내용의 제목을 나타내는 hn 태그 중 하나를 포함합니다.
```HTML
<section></section>
```

### 3.9.4 article 태그
`article 태그`는 웹 페이지에서 독립적인 영역을 구분할 때 사용합니다.
```HTML
<article></article>
```

section 태그는 웹 페이지 안에서 관련 있는 내용을 구분하고, article 태그는 어떤 웹 페이지에서든 독립적으로 사용될 수 있는 영역을 구분한다는 차이점이 있습니다.

### 3.9.5 aside 태그
`aside 태그`는 웹 페이지 안에서 주력 내용이나 독립적인 내용으로 보기 어려워서 article 태그나 section 태그로 영역을 구분할 수 없을 때 사용합니다.
```HTML
<aside></aside>
```
### 3.9.6 footer 태그
`footer 태그`는 웹 페이지에서 푸터 영역을 구분할 때 사용합니다. 푸터 영역은 일반적으로 페이지의 최하단에 있고, 저작권 정보, 연락처, 사이트 맵 등의 요소들을 포함합니다.

### 3.9.7 main 태그
`main 태그`는 웹 페이지의 주요 내용을 지정할 때 사용하는 태그입니다. main 태그에는 문서에 반복해서 등장하는 요소를 포함해선 안 됩니다. 그리고 main 태그를 article, aside, footer, header, nav 태그의 하위에 포함할 수도 없습니다.

## 3.10 태그 종류에 상관없이 사용하는 글로벌 속성
HTML 언어에서 태그는 각 태그에서 사용할 수 있는 속성이 정해져 있는데 `글로벌 속성(global attribute)`은 태그 종류 상관없이 모든 태그에서 공통으로 사용할 수 있는 속성을 말합니다.

자주 사용하는 글로벌 속성

| 속성 | 값 | 설명 |
| ---- | ---- | ---- |
| class | value | 요소에 클래스 값을 지정합니다. 클래스 값은 CSS에서 클래스 선택자로 활용합니다. |
| id | value | 요소에 아이디 값을 지정합니다. 아이디 값은 CSS에서 아이디 선택자로 활용합니다. |
| style | style | 요소에 인라인 스타일을 지정합니다. |
| title | text | 요소에 추가 정보를 지정합니다. 마우스를 요소 위에 올리면 툴팁(tooltip)으로 추가 정보가 표시됩니다. 툴팁은 요소에 마우스 커서를 올렸을 때 추가 설명이 뜨는 말풍선 형태의 그래픽 요소를 말합니다. |
| lang | language code | 요소에 사용한 텍스트의 언어 정보를 지정합니다. |
| hidden  | hidden | 요소를 화면에서 감춥니다. |
| data-* | value | 사용자가 임의의 속성을 만들 수 있습니다. |

- class 속성
`class 속성`은 요소에 클래스명을 지정할 때 사용합니다. 클래스명은 CSS에서 클래스 선택자로 활용하고, 같은 클래스명은 여러 요소가 중복해서 가질 수 있습니다.
```HTML
<p class="red-color">...</p>
```

- id 속성
id 속성은 요소에 아이디를 지정할 때 사용합니다. 아이디는 CSS에서 아이디 선택자로 활용하며, 중복될 수 없습니다.
```HTML
<h1 id="title">...</h1>
```

- style 속성
style 속성은 CSS 코드를 인라인으로 작성할 때 사용합니다.

- title 속성
title 속성은 요소에 추가 정보를 넣을 때 사용합니다. title 속성에 넣은 값은 요소에 마우스를 올리면 툴팁으로 표시됩니다.
```HTML
<p><span title="World Wide Web Consortium'>W3C</span>는 국제 웹 표준 개발 기구입니다.</p>
```

- lang 속성
`lang 속성`은 요소에 사용한 텍스트의 언어 코드를 지정할 때 사용합니다. 일반적으로 HTML 문서의 언어 코드는 html 태그의 lang 속성에 작성합니다.
```HTML
<html lang="ko">
```

lang 속성으로 웹 접근성을 높일 수 있습니다.

- data-* 속성
`date-* 속성`은 사용자 커스텀 속성을 만듭니다. 태그에서 사용할 수 있는 속성은 HTML 문법에서 정해져 있어서 정해진 속성이 아니면 사용할 수 없습니다. 그러나 HTML5에서는 이러한 점이 개선되어 data-* 속성으로 사용자가 원하는 속성을 만들 수 있습니다.

HTML에는 data-name과 data-hero라는 속성이 존재하지 않지만, 다음 코드처럼 data-* 속성으로 새로 만들 수 있습니다.
```HTML
<p data-name="spiderMan" data-hero="ture">...</p>
```

---

# Python
---
## 05-4 예외 처리

### 오류는 언제 발생하는가?

존재하지 않는 파일을 사용하려고 시도했을 때 발생하는 오류
```Python
f = open("나없는파일", 'r')
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# FileNotFoundError: [Error 2] No such file or directory: '나없는파일'
```
위 예에서 볼 수 있듯이 없는 파일을 열려고 시도하면 `FileNotFoundError` 오류가 발생한다.

이번에는 0으로 다른 숫자를 나누는 경우를 생각해 보자. 이 역시 자주 발생하는 오류이다.
```Python
4 / 0
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ZeroDivisionError: division by zero
```
4를 0으로 나누려고 하니 `ZeroDivisionError` 오류가 발생한다.

마지막으로 1가지 예를 더 들어 보자.
```Python
a = [1, 2, 3]
a[3]
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# IndexError: list index out of range
```
a\[3]은 a의 네 번째 요솟값을 가리키는데, a 리스트에는 값이 3개밖에 없으므로 (\[1, 2, 3]) 값을 얻을 수 없다. 따라서 `IndexError` 오류가 발생한다. 파이썬은 이런 오류가 발생하면 프로그램을 중단하고 오류 메시지를 보여 준다.

### 오류 예외 처리 기법

#### try-except 문
다음은 오류를 처리하기 위한 try-except 문의 기본 구조이다.
```Python
try:
	...
except [발생_오류 [as 오류_변수]]:
	...
```

try 블록 수행 중 오류가 발생하면 except 블록이 수행된다. 하지만 try 블록에서 오류가 발생하지 않는다면 except 블록은 수행되지 않는다.

except 구문은 다음 3가지 발법으로 사용할 수 있다.
1. try-except만 쓰는 방법
```Python
try:
    ...
except:
	...
```
이 경우에는 오류의 종류에 상관없이 오류가 발생하면 except 블록을 수행한다.

2. 발생 오류만 포함한 except 문
```Python
try:
	...
except 발생_오류:
	...
```
이 경우는 오류가 발생했을 때 except 문에 미리 정해 놓은 오류와 동일한 오류일 경우에만 except 블록을 수행한다는 뜻이다.

3. 발생 오류와 오류 변수까지 포함한 except 문
```Python
try:
	...
except 발생_오류 as 오류_변수:
	...
```
이 경우는 두 번째 경우에서 오류의 내용까지 알고 싶을 때 사용하는 방법이다.

```Python
try:
	4 / 0
except ZeroDivisionError as e
	print(e)

# ZeroDivisionError
```

위처럼 4를 0으로 나누려고 하면 ZeroDivisionError가 발생하여 except 블록이 실행되고 오류 변수 e에 담기는 오류 메시지를 출력할 수 있다.

#### try-finally 문
try 문에는 finally 절을 사용할 수 있다. finally 절은 try 문 수행 도중 예외 발생 여부에 상관없이 항상 수행된다. 보통 finally 절은 사용한 리소스를 close해야 할 때 많이 사용한다.

```Python
try:
	f = open('foo.txt', 'w')
	# 무언가를 수행
	(...생략...)

finally:
	f.close()    # 중간에 오류가 발생하더라도 무조건 실행
```

foo. txt 파일을 쓰기 모드로 연 후 예외 발생 여부에 상관없이 항상 파일을 닫아 주려면 try-finally 문을 사용하면 된다.

#### 여러 개의 오류 처리하기
try 문 안에서 여러 개의 오류를 처리하려면 다음과 같이 사용해야 한다.

```Python
try:
    ...
except 발생_오류1:
	...
except 발생_오류2:
	...
```

즉, 0으로 나누는 오류와 인덱싱 오류를 다음과 같이 처리할 수 있다.

```Python
try:
	a = [1, 2]
	print(a[3])
	4 / 0
except ZeroDivisionError:
	print("0으로 나눌 수 없습니다.")
except IndexError:
	print("인덱싱할 수 없습니다.")
```

a는 2개의 요솟값을 가지고 있으므로 a\[3]이 IndexError를 발생시켜 "인덱싱할 수 없습니다."라는 문자열을 출력할 것이다. 인덱싱 오류가 먼저 발생했으므로 4 / 0에 따른 ZeroDivisionError 오류는 발생하지 않는다.

다음과 같이 ZerroDivisionError와 IndexError를 함께 처리할 수도 있다.

```Python
try:
	a = [1, 2]
	print(a[3])
	4 / 0
except (ZeroDivisionError, IndexError) as e:
	print(e)
```

2개 이상의 오류를 동일하게 처리하기 위해서는 위와 같이 괄호를 사용하여 함께 묶어 처리하면 된다.

#### try-else 문
try 문에는 다음처럼 else 절을 사용할 수도 있다.

```Python
try:
	...
except [발생_오류 [as 오류_변수]]:
	...
else:    # 오류가 없을 경우에만 수행
	...
```

try 문 수행 중 오류가 발생하면 except 절, 오류가 발생하지 않으면 else 절이 수행된다.

다음은 try 문에 else 절을 사용한 간단한 예제이다.

```Python
try:
	age = int(input('나이를 입력하세요: '))
except:
	print('입력이 정확하지 않습니다.')
else:
	if age <= 18:
		print('미성년자는 출입금지입니다.')
	else:
		print('환영합니다.')
```

### 오류 회피하기
코드를 작성하다 보면 특정 오류가 발생할 경우 그냥 통과시켜야 할 때가 있다. 다음 예를 살펴보자.

```Python
try:
	f = open("나없는파일", 'r')
except FileNotFoundError:    # 파일이 없더라도 오류가 발생하지 않고 통과
	pass
```

try 문 안에서 FileNotFountError가 발생할 경우, `pass`를 사용하여 오류를 그냥 회피하도록 작성한 예제이다.

### 오류 일부러 발생시키기
프로그래밍을 하다 보면 종종 오류를 일부러 발생시켜야 할 경우도 생긴다. 파이썬은 raise 명령어를 사용해 오류를 강제로 발생시킬 수 있다.

예를 들어 Bird 클래스를 상속받는 자식 클래스는 반드시 fly라는 함수를 구현하도록 만들고 싶은 경우(강제로 그렇게 하고 싶은 경우)가 있을 수 있다. 다음 예를 살펴보자

```Python
class Bird:
	def fly(self):
		raise NotImplementedError
```

Bird 클래스를 상속받는 자식 클래스는 반드시 fly 함수를 구현해야 한다는 의지를 보여준다. 만약 자식 클래스가 fly 함수를 구현하지 않은 상태로 fly 함수를 호출한다면 어떻게 될까?

> NotImplementedError는 파이썬에 이미 정의되어 있는 오류로, 꼭 작성해야 하는 부분이 구현되지 않았을 경우 일부러 오류를 발생시키기 위해 사용한다.


```Python
class Eagle(Bird):
	pass

eagle = Eagle()
eagle.fly()
```

Eagle 클래스는 Bird 클래스를 상속받았다. 그런데 Eagle 클래스는 fly 메서드를 오버라이딩하여 구현하지 않았다. 따라서 eagle 객체의 fly 메서드를 수행하는 순간, Bird 클래스의 fly 메서드가 수행되어 NotImplementedError가 발생한다.

NotImplementedError가 발생하지 않게 하려면 다음과 같이 Eagle 클래스에 fly 함수를 구현해야 한다.
```Python
class Eagle(Bird):
	def fly(self):
		print("very fast")

eagle = Eagle()
eagle.fly()
# Very fast
```

위 예처럼 fly 함수를 구현한 후 프로그램을 실행하면 오류 없이 다음 문장이 출력된다.

### 예외 만들기
프로그램을 수행하다가 특수한 경우에만 예외 처리를 하려고 종종 예외를 만들어서 사용한다. 이번에는 직접 예외를 만들어 보자.

예외는 다음과 같이 파이썬 내장 클래스인 `Exception 클래스`를 상속하여 만들 수 있다.

```Python
class MyError(Exception):
	pass

def say_nick(nick):
	if nick == '바보':
		raise MyError()
	print(nick)
```

그리고 다음과 같이 say_nick 함수를 호출해 보자.
```Python
say_nick("천사")
say_nick("바보")
```

저장한 후 프로그램을 실행해 보면 "천사"가 한 번 출력된 후 MyError가 발생한다.

이번에는 예외 철 기법을 사용하여 MyError 발생을 예외 처리해 보자. 프로그램을 실행하면 다음과 같이 출력된다.
```Python
try:
	say_nick("천사")
	say_nick("바보")
except MyError:
	print("허용되지 않는 별명입니다.")
# 천사
# 허용되지 않는 별명입니다.
```

만약 오류 메시지를 사용하고 싶다면 다음처럼 예외 처리를 하면 된다.
```Python
try:
	say_nick("천사")
	say_nick("바보")
except MyError as e:
	print(e)
```

하지만 프로그램을 실행해 보면 print(e)로 오류 메시지가 출력되지 않는 것을 확인할 수 있다. 오류 메시지를 출력했을 때 오류 메시지가 보이게 하려면 오류 클래스에 다음과 같은 \_\_str\_\_ 메서드를 구현해야 한다. \_\_str\_\_ 메서드는 print(e)처럼 오류 메시지를 print문으로 출력할 경우에 호출되는 메서드이다.

```Python
class MyError(Exception):
	def __str__(self):
		return "허용되지 않는 별명입니다."
```

## 05-5 내장 함수
`파이썬 내장(built-in) 함수`는 파이썬 모듈과 달리 import가 필요하지 않기 때문에 아무런 설정 없이 바로 사용할 수 있다.

### abs
`abs(x)`는 어떤 숫자를 입력받았을 때 그 숫자의 절댓값을 리턴하는 함수이다.
```Python
abs(3)
# 3
abs(-3)
# 3
abs(-1.2)
# 1.2
```

### all
`all(x)`는 반복 가능한 데이터 x를 입력값으로 받으며 이 x의 요소가 모두 참이면 True, 거짓이 하나라도 있으면 False를 리턴한다.

> 반복 가능한 데이터란 for 문에서 사용할 수 있는 자료형을 의미한다. 리스트, 튜플, 문자열, 딕셔너리, 집합 등이 있다.

다음 예를 살펴보자.
```Python
all([1, 2, 3])
# True
```

리스트 \[1, 2, 3]은 모든 요소가 참이므로 True를 리턴한다.

```Python
all([1, 2, 3, 0])
# False
```

리스트 \[1, 2, 3, 0] 중에서 요소 0은 거짓이므로 False를 리턴한다.

```Python
all([])
True
```

만약 all의 입력 인수가 빈 값인 경우에는 True를 리턴한다.
